In [1]:
import numpy as np
import random

from sympy import *

# Заполнение матриц

In [2]:
X1 = np.array([[random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)],
              [random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)],
              [random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)],
              [random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)]])
X1

array([[26,  9,  0, 78],
       [60, 49, 25, 20],
       [12, 33, 94, 94],
       [55, 80, 33, 73]])

In [3]:
X2 = np.array([[random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)],
              [random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)],
              [random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)],
              [random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)]])
X2

array([[92, 62, 44, 70],
       [87, 99, 96, 73],
       [31, 11, 82, 49],
       [79, 95, 49, 55]])

# Математические операции

In [4]:
X_sum = X1 + X2
X_sum

array([[118,  71,  44, 148],
       [147, 148, 121,  93],
       [ 43,  44, 176, 143],
       [134, 175,  82, 128]])

In [5]:
X_mul = X1 * X2
X_mul

array([[2392,  558,    0, 5460],
       [5220, 4851, 2400, 1460],
       [ 372,  363, 7708, 4606],
       [4345, 7600, 1617, 4015]])

In [6]:
X_dif = X1 - X2
X_dif

array([[-66, -53, -44,   8],
       [-27, -50, -71, -53],
       [-19,  22,  12,  45],
       [-24, -15, -16,  18]])

In [7]:
X_rat = X1 / X2
X_rat

array([[0.2826087 , 0.14516129, 0.        , 1.11428571],
       [0.68965517, 0.49494949, 0.26041667, 0.2739726 ],
       [0.38709677, 3.        , 1.14634146, 1.91836735],
       [0.69620253, 0.84210526, 0.67346939, 1.32727273]])

# Определители и обратные матрицы

In [8]:
X1_det = np.linalg.det(X1)
X1_det

16149142.000000017

In [9]:
X2_det = np.linalg.det(X2)
X2_det

898920.0000000013

In [10]:
X1_rev = np.linalg.inv(X1)
X1_rev

array([[ 0.01135633,  0.02896612, -0.00120062, -0.01852408],
       [-0.01470481, -0.01700474, -0.00479778,  0.02654878],
       [-0.0070192 ,  0.00996524,  0.0115221 , -0.01006691],
       [ 0.01073178, -0.00769329,  0.0009538 ,  0.00311137]])

In [11]:
X2_rev = np.linalg.inv(X2)
X2_rev

array([[ 0.07594447,  0.22094513, -0.14204156, -0.26336493],
       [-0.03271926, -0.06429716,  0.03625017,  0.09468696],
       [ 0.01516486,  0.10344413, -0.05018912, -0.11188537],
       [-0.0660793 , -0.29845815,  0.18612335,  0.33259912]])

# Проверка обратных матриц

In [12]:
E1 = X1 @ X1_rev
E1.round()

array([[ 1., -0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1.,  0.],
       [ 0., -0.,  0.,  1.]])

In [13]:
E2 = X2 @ X2_rev
E2.round()

array([[ 1.,  0.,  0., -0.],
       [ 0.,  1.,  0., -0.],
       [ 0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

# Решение линейный уравнений

In [14]:
Y1 = np.array([random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)])
Y1

array([24, 63, 75,  5])

In [15]:
Y2 = np.array([random.randint(0,99),random.randint(0,99),random.randint(0,99),random.randint(0,99)])
Y2

array([80, 34, 99,  0])

In [16]:
X1_lin = np.linalg.solve(X1, Y1)
X1_lin

array([ 1.91475058, -1.65130358,  1.27317191, -0.14002286])

In [17]:
X2_lin = np.linalg.solve(X2, Y2)
X2_lin

array([-0.47442264, -1.21487785, -0.23843279,  2.99229075])

# Проверка решения линейный уравнений

In [18]:
X1_test = np.dot(X1, X1_lin)
X1_test

array([24., 63., 75.,  5.])

In [19]:
X1_test = X1 @ X1_lin
X1_test

array([24., 63., 75.,  5.])

In [22]:
X2_test = np.dot(X2, X2_lin)
X2_test.round()

array([80., 34., 99.,  0.])

In [21]:
X2_test = X1 @ X1_lin
X2_test

array([24., 63., 75.,  5.])